import {
  ContractAllianceOpsStablesAllowedRecipientsRegistry,
  ContractAllowedRecipientReferralDaiRegistry,
  ContractAllowedRecipientRegistry,
  ContractAllowedRecipientTrpLdoRegistry,
  ContractAragonAcl,
  ContractAtcStablesRegistry,
  ContractAtcStethAllowedRecipientsRegistry,
  ContractEasyTrack,
  ContractEcosystemOpsStablesAllowedRecipientsRegistry,
  ContractEcosystemOpsStethAllowedRecipientsRegistry,
  ContractGasFunderETHRegistry,
  ContractGovernanceToken,
  ContractLabsOpsStablesAllowedRecipientsRegistry,
  ContractLabsOpsStethAllowedRecipientsRegistry,
  ContractLegoLDORegistry,
  ContractLegoStablesRegistry,
  ContractPmlStablesRegistry,
  ContractPmlStethAllowedRecipientsRegistry,
  ContractRccStablesRegistry,
  ContractRccStethAllowedRecipientsRegistry,
  ContractReferralPartnersRegistry,
  ContractRewardsShareProgramRegistry,
  ContractSandboxStablesAllowedRecipientRegistry,
  ContractStethGasSupplyRegistry,
  ContractStethRewardProgramRegistry,
  ContractStonksStablesAllowedRecipientsRegistry,
  ContractStonksStethAllowedRecipientsRegistry,
} from './contracts'

export const DEFAULT_DECIMALS = 18
export const GET_LOG_BLOCK_LIMIT = 4999

export const allowedEventContracts = [
  ContractLegoLDORegistry,
  ContractLegoStablesRegistry,
  ContractPmlStablesRegistry,
  ContractAtcStablesRegistry,
  ContractGasFunderETHRegistry,
  ContractAllowedRecipientRegistry,
  ContractAllowedRecipientReferralDaiRegistry,
  ContractAllowedRecipientTrpLdoRegistry,
  ContractStethRewardProgramRegistry,
  ContractStethGasSupplyRegistry,
  ContractRewardsShareProgramRegistry,
  ContractRccStablesRegistry,
  ContractSandboxStablesAllowedRecipientRegistry,
  ContractRccStethAllowedRecipientsRegistry,
  ContractPmlStethAllowedRecipientsRegistry,
  ContractAtcStethAllowedRecipientsRegistry,
  ContractStonksStethAllowedRecipientsRegistry,
  ContractStonksStablesAllowedRecipientsRegistry,
  ContractAllianceOpsStablesAllowedRecipientsRegistry,
  ContractEcosystemOpsStablesAllowedRecipientsRegistry,
  ContractEcosystemOpsStethAllowedRecipientsRegistry,
  ContractLabsOpsStablesAllowedRecipientsRegistry,
  ContractLabsOpsStethAllowedRecipientsRegistry,
  ContractEasyTrack,
  ContractAragonAcl,
  ContractReferralPartnersRegistry,
  ContractGovernanceToken,
]
